/**
 * Skill `registrar_intencao_fechamento` — aceite + carrinho + draft.
 *
 * Quando: cliente sinaliza fechamento ("vou levar", "pode fechar", "vou ficar com"),
 * ou está preenchendo dados de fechamento (nome, endereço, pagamento, modalidade),
 * ou pede pra mexer no carrinho (tirar/mudar/cancelar item).
 *
 * Tools típicas: geralmente NENHUMA (state já tem). As vezes calcularFrete pra confirmar entrega.
 *
 * Exemplos focados (9):
 *   6. Closing intent + pix sem dados completos
 *  10. Closing parcial (ack + draft)
 *  11. Intenção de fechamento SEM tools (cliente aceitou cotação anterior)
 *  12. Despedida pós-fechamento
 *  13. Nome + endereço grudados na frase (separe!)
 *  15. Cliente fechou MULTIPLOS items, pergunta total → add_to_cart x N
 *  16. Cliente pergunta total ANTES de aceitar (estimativa, NÃO add_to_cart)
 *  17. Tira UM item do carrinho (remove_from_cart)
 *  18. Muda quantidade (update_cart_item)
 *  19. Cancela TUDO (clear_cart)
 */

export const SKILL_REGISTRAR_INTENCAO_FECHAMENTO_EXAMPLES = [
  '# Exemplos da skill registrar_intencao_fechamento',
  '',
  '## Exemplo 6 — Closing intent + pix com produto cotado no mesmo turn',
  'Customer: "Minha moto é Zontes R310 2024. Traseiro 160/60R17. Se tiver, passo no pix hoje."',
  'tool_results: buscarProduto (P6=R$120), verificarEstoque (P6 disponível)',
  '{',
  '  "say": "Achei o 160/60R17 traseiro por R$ 120,00 e tem em estoque. Anotei pagamento via Pix. Me passa seu nome pra eu separar?",',
  '  "actions": [',
  '    create_item ITEM_A, update_slot item ITEM_A moto_modelo="R310", moto_ano=2024, medida_pneu="160/60R17", posicao_pneu="rear",',
  '    update_slot global forma_pagamento="pix",',
  '    { "type": "update_draft", "payment_method": "pix" }',
  '  ],',
  '  "claims": [',
  '    { "type": "price", "amount": 120, "product_id": "P6" },',
  '    { "type": "stock_availability", "product_id": "P6" }',
  '  ],',
  '  "rationale": "Closing sinalizado, draft com pix. Falta nome. Cita produto/estoque com claims."',
  '}',
  '',
  '## Exemplo 10 — Fechamento parcial (ack + draft sem afirmar comercial)',
  'Customer: "Pode separar o 110/70-17, pago pix e busco hoje."',
  'tool_results: depende — pode não ter rodado nesse turno (continuação de turno anterior)',
  '{',
  '  "say": "Anotei: separar 110/70-17, pagamento Pix, retirada hoje. Me passa seu nome pra registrar?",',
  '  "actions": [',
  '    update_slot global forma_pagamento="pix",',
  '    { "type": "update_draft", "payment_method": "pix", "fulfillment_mode": "pickup" }',
  '  ],',
  '  "claims": [],',
  '  "rationale": "Fechamento parcial: registra pagamento e pickup, pede nome. Nao afirma comercial novo, sem claim."',
  '}',
  '',
  '## Exemplo 11 — Aceite sem tool nova (cliente aceitou cotacao anterior)',
  'Frases de aceite: "blz vou querer", "vou ficar com esse", "pode fechar", "fica esse mesmo", "manda esse", "pode separar" (lista no common).',
  'state.items tem produto cotado em turn anterior. tool_results deste turn: NENHUMA.',
  '{',
  '  "say": "Show! Anotei. Me passa seu nome completo e o endereço pra entrega em Bangu (rua, número).",',
  '  "actions": [',
  '    { "type": "add_to_cart", "product_id": "<uuid_do_produto_cotado>", "quantity": 1, "unit_price": <preco_cotado> },',
  '    { "type": "update_draft", "fulfillment_mode": "delivery" }',
  '  ],',
  '  "claims": [],',
  '  "rationale": "Aceite explicito de produto cotado antes. product_id vem do historico. Sem claim novo (valor cotado/validado antes)."',
  '}',
  '',
  '## Exemplo 12 — Despedida pos-fechamento',
  'Customer: "Opa valeu"  (ou "obrigado", "blz amigo", "tmj")',
  'tool_results: NENHUMA.',
  '{',
  '  "say": "Disponha! Qualquer coisa é só chamar.",',
  '  "actions": [],',
  '  "claims": [],',
  '  "rationale": "Despedida apos fechamento. Encerro com cordialidade. Sem actions porque nao tem dado novo. Sem fallback — despedida nao eh falta de dado."',
  '}',
  '',
  '## Exemplo 13 — Nome + endereco grudados (separar + confirmar completo)',
  'Separe nome (so o nome) de endereco (rua/numero/bairro). Confirme endereco COMPLETO incluindo cidade do state (Show, dont ask).',
  'Customer: "Anderson Tavares endereço rua vagabanda n 656 bangu"',
  'state.global_slots: municipio="Rio de Janeiro" (de calcularFrete anterior)',
  '{',
  '  "say": "Anotei, Anderson Tavares. Endereço: Rua Vagabanda nº 656, Bangu, Rio de Janeiro. Tá certo?",',
  '  "actions": [',
  '    update_slot global nome="Anderson Tavares", update_slot global bairro="Bangu",',
  '    { "type": "update_draft", "customer_name": "Anderson Tavares", "delivery_address": "Rua Vagabanda nº 656, Bangu, Rio de Janeiro", "fulfillment_mode": "delivery" }',
  '  ],',
  '  "claims": [],',
  '  "rationale": "Separo nome/endereco. Cidade do state. Cliente confirma/corrige."',
  '}',
  '',
  '## Exemplo 13b — Pagamento generico → mostra parcelas direto',
  'Customer: "vou pagar no cartao"',
  '{',
  '  "say": "Anotei. Cartao credito (aceitamos ate 3x sem juros) ou debito?",',
  '  "actions": [ update_slot global forma_pagamento="cartao" ],',
  '  "claims": [],',
  '  "rationale": "Cartao generico. Mostro parcelas (politica) ja na pergunta — cliente decide informado."',
  '}',
  '',
  '## Exemplo 15 — Aceite multi-item (total preemptivo)',
  '2 items cotados antes (140/70-17 R$99, 80/100-18 R$99), frete R$9,90. Cliente aceita.',
  'Customer: "blz pode fechar" (ou "vou querer os 2", "fechado")',
  '{',
  '  "say": "Show. Fechado os 2: o 140/70-17 R$ 99,00 e o 80/100-18 R$ 99,00. Com frete R$ 9,90, total R$ 207,90. Me passa seu nome pra eu separar?",',
  '  "actions": [',
  '    { "type": "add_to_cart", "product_id": "<uuid_traseiro>", "quantity": 1, "unit_price": 99 },',
  '    { "type": "add_to_cart", "product_id": "<uuid_dianteiro>", "quantity": 1, "unit_price": 99 }',
  '  ],',
  '  "claims": [],',
  '  "rationale": "Multi-item aceito. 2 add_to_cart qty=1. Total preemptivo 207,90 (sem cliente perguntar). Sem claim novo."',
  '}',
  '',
  '## Exemplo 16 — Cliente pergunta total DURANTE coleta, sem fechar ainda',
  'Cenario: 1 item cotado, cliente em meio da coleta de endereco. Cliente pergunta "quanto vai dar tudo?" ANTES de aceitar.',
  '{',
  '  "say": "Pelo que temos ate aqui: o 130/70-13 R$ 99,00 + frete R$ 9,90 = R$ 108,90. Posso confirmar?",',
  '  "actions": [],',
  '  "claims": [],',
  '  "rationale": "Pediu total sem aceitar. Mostro estimativa. NAO add_to_cart antes de aceite explicito."',
  '}',
  '',
  '## Exemplo 17 — Tira UM item (cita QUAL + preco)',
  'state.cart: CART_A dianteiro 80/100-18 R$99, CART_B traseiro 90/90-18 R$99. Cliente desiste do traseiro.',
  'Customer: "esquece o traseiro, vou levar so o dianteiro"',
  '{',
  '  "say": "Show, tirei o 90/90-18 traseiro (R$ 99,00). Fica so o 80/100-18 dianteiro (R$ 99,00). Total agora R$ 99,00 + frete. Mantem o resto?",',
  '  "actions": [ { "type": "remove_from_cart", "cart_item_id": "CART_B" } ],',
  '  "claims": [],',
  '  "rationale": "Removi traseiro. Cito item+preco removido + total novo. Sem claim."',
  '}',
  '',
  '## Exemplo 18 — Muda quantidade (qty=TOTAL desejado, nao incremento)',
  'state.cart: CART_A 130/70-13 qty=1 R$99. Cliente quer 2.',
  'Customer: "vou levar 2 desse mesmo"',
  '{',
  '  "say": "Beleza, 2 unidades do 130/70-13 (R$ 99,00 cada). Total R$ 198,00 + frete. Confirma?",',
  '  "actions": [ { "type": "update_cart_item", "cart_item_id": "CART_A", "quantity": 2 } ],',
  '  "claims": [],',
  '  "rationale": "Subiu pra 2. Cito unitario+total. quantity=2 (total, nao incremento)."',
  '}',
  '',
  '## Exemplo 19 — Cancela TUDO (lista o que cancelou)',
  'state.cart: 2 items, total R$ 198. Cliente desiste.',
  'Customer: "esquece, deixa pra outro dia" (ou "cancela tudo", "muda de ideia")',
  '{',
  '  "say": "Tranquilo, cancelei o pedido (2 pneus, R$ 198,00). Qualquer coisa, e so chamar.",',
  '  "actions": [ { "type": "clear_cart" } ],',
  '  "claims": [],',
  '  "rationale": "Cancelou explicito. Listo o que cancelei. Se ambiguo (\\"hmm nao sei\\"), pergunte antes."',
  '}',
].join('\n');
