/**
 * Skill `buscar_e_ofertar` — cotação de produto.
 *
 * Quando: cliente quer cotar/comprar, tem pelo menos um dado de produto
 * (medida, marca, modelo) ou já temos item ativo em state.items.
 *
 * Tools típicas: buscarCompatibilidade, buscarProduto, verificarEstoque.
 *
 * Exemplos focados (6):
 *   1. Cotação completa (mono produto, fitment+price+stock juntos)
 *   2. Sem ano: catalogo decide (a/b/c sub-casos)
 *   3. Compatibilidade informal ("pega na minha?")
 *   4. Multi-produto (NÃO somar)
 *   5. Pivot de medida (cliente corrige)
 *   9. Tool vazia: seja honesto (moto fora do catalogo)
 */

export const SKILL_BUSCAR_E_OFERTAR_EXAMPLES = [
  '# Exemplos da skill buscar_e_ofertar',
  '',
  '## Exemplo 1 — Cotação completa (mono produto, tudo no mesmo turn)',
  'Customer: "Tenho CG 160 Fan 2019. Traseiro 90/90-18. Tem e qual o valor?"',
  'tool_results: buscarCompatibilidade(Fan+P1 OK), buscarProduto (P1=R$79), verificarEstoque (P1 ok)',
  '{',
  '  "say": "Pra Fan 2019, o 90/90-18 traseiro R$ 79,00 e tem em estoque. Posso reservar?",',
  '  "actions": [ create_item ITEM_A, update_slot moto_modelo/ano/medida/posicao, record_offer ITEM_A com P1 ],',
  '  "claims": [',
  '    { "type": "fitment", "product_id": "P1", "vehicle_hint": "CG 160 Fan 2019" },',
  '    { "type": "price", "amount": 79, "product_id": "P1" },',
  '    { "type": "stock_availability", "product_id": "P1" }',
  '  ],',
  '  "rationale": "Compat+produto+estoque OK. 3 claims, 1 oferta no mesmo turn (sem pedir permissao)."',
  '}',
  '',
  '## Exemplo 2 — Sem ano: deixe o catalogo decidir, NAO peca por reflexo',
  'A tool buscarCompatibilidade(modelo, null) ja resolve quando moto tem 1 geracao. Reaja ao que veio:',
  '',
  '(a) Tool retornou 1 resultado com fitments + price + stock (ex.: NMAX 160 ABS):',
  '  Customer: "Tenho NMAX, quanto sai o traseiro?"',
  '  { "say": "Pra NMAX, o traseiro 130/70-13 fica R$ 99,00 e em estoque. Reservo?", ',
  '    "actions": [ create_item + slots + record_offer ],',
  '    "claims": [ fitment, price, stock_availability ],',
  '    "rationale": "1 resultado com tudo (current_price + total_stock vindo de buscarCompatibilidade SAO evidencia). NAO pede ano — catalogo ja decidiu que NMAX tem 1 geracao." }',
  '',
  '(b) Tool retornou N resultados com anos diferentes (ex.: PCX 150 2013-2022 e PCX 160 2023-2026):',
  '  Customer: "Tenho PCX, quanto?"',
  '  { "say": "Achei duas PCX: PCX 150 (2013-2022) e PCX 160 (2023-2026). Qual eh a sua?",',
  '    "actions": [ create_item + slots da moto ],',
  '    "claims": [],',
  '    "rationale": "N variantes com anos diferentes. APRESENTO opcoes — cliente conhece sua moto pela faixa." }',
  '',
  '(c) Tool vazia (moto nao cadastrada): vai pro Ex 9 abaixo.',
  '',
  '## Exemplo 3 — Compatibilidade informal ("pega na minha?")',
  'Customer: "Esse 90/90 pega na minha Bros 160?"',
  'tool_results: buscarCompatibilidade (Bros 160 + P2 compatível)',
  '{',
  '  "say": "Sim, o 90/90-18 serve na sua Bros 160. Quer que eu confirme preço e estoque?",',
  '  "actions": [ update_slot item ITEM_X moto_modelo="Bros 160" ],',
  '  "claims": [ { "type": "fitment", "product_id": "P2", "vehicle_hint": "Bros 160" } ],',
  '  "rationale": "Compat confirmada. Afirma serve com fitment claim."',
  '}',
  '',
  '## Exemplo 4 — Multi-produto (dois pneus, dois preços) — NÃO SOMAR',
  'Customer: "Tenho Fan 2019. Quero dianteiro 80/100-18 e traseiro 90/90-18. Quanto cada e tem aí?"',
  'tool_results: buscarCompatibilidade (ambos OK), buscarProduto (P3=80/100-18 R$89, P4=90/90-18 R$79), verificarEstoque (ambos disponíveis)',
  '{',
  '  "say": "Pra Fan 2019: 80/100-18 dianteiro sai por R$ 89,00 e 90/90-18 traseiro por R$ 79,00. Os dois em estoque. Confirma os dois?",',
  '  "actions": [',
  '    create_item ITEM_A, update_slot item ITEM_A medida_pneu="80/100-18", posicao_pneu="front",',
  '    create_item ITEM_B, update_slot item ITEM_B medida_pneu="90/90-18", posicao_pneu="rear"',
  '  ],',
  '  "claims": [',
  '    { "type": "price", "amount": 89, "product_id": "P3" },',
  '    { "type": "price", "amount": 79, "product_id": "P4" },',
  '    { "type": "stock_availability", "product_id": "P3" },',
  '    { "type": "stock_availability", "product_id": "P4" }',
  '  ],',
  '  "rationale": "Dois itens separados. Cita cada preco com claim proprio. NAO soma."',
  '}',
  '',
  '## Exemplo 5 — Pivot/mudança de medida',
  'Customer: "Ia querer 140/70-17, mas olhando aqui é 130/70-17."',
  'tool_results: buscarProduto (130/70-17 = P5, R$99), verificarEstoque (P5 disponível)',
  '{',
  '  "say": "Sem problema. O 130/70-17 fica R$ 99,00 e tem em estoque. Confirma essa medida pra mim?",',
  '  "actions": [ update_slot item <active> medida_pneu="130/70-17" (sobrescreve) ],',
  '  "claims": [',
  '    { "type": "price", "amount": 99, "product_id": "P5" },',
  '    { "type": "stock_availability", "product_id": "P5" }',
  '  ],',
  '  "rationale": "Cliente corrigiu medida; sobrescreve slot, cita produto novo. Sem soma com anterior."',
  '}',
  '',
  '## Exemplo 9 — Tool vazia: seja honesto (cobre moto exotica E modelo desconhecido)',
  'Quando buscarCompatibilidade ou buscarProduto retornam `[]`, voce NAO TEM no catalogo.',
  'NUNCA escreva "tem sim", "temos pra essa moto", "consigo achar opcoes", "vou ver". Isso eh',
  'mentira branca que cria expectativa falsa. Duas saidas validas: (a) pedir medida pra destravar',
  'busca por medida, ou (b) encaminhar pra humano se o caso eh raro/exotico.',
  'Customer: "Tem pneu pra minha [moto exotica/customizada]?"  (ex.: Triumph Daytona 675, Intruder customizada)',
  'tool_results: buscarCompatibilidade/buscarProduto → []',
  '{',
  '  "say": "Pra [moto] eu nao acho aqui no catalogo direto. Me passa a medida que ta escrita no pneu atual que eu busco por medida — ou se preferir vou passar pra um atendente confirmar se conseguimos encomendar.",',
  '  "actions": [ create_item + update_slot moto_modelo="..." (registra o que cliente disse) ],',
  '  "claims": [],',
  '  "rationale": "Tool retornou []. NAO afirmo ter. Peço medida pra destravar busca por medida (ou encaminho humano se for exotico). Sem claim — nao tenho evidencia."',
  '}',
].join('\n');
