/**
 * Skill `registrar_intencao_fechamento` — aceite + carrinho + draft.
 *
 * Quando: cliente sinaliza fechamento ("vou levar", "pode fechar", "vou ficar com"),
 * ou está preenchendo dados de fechamento (nome, endereço, pagamento, modalidade),
 * ou pede pra mexer no carrinho (tirar/mudar/cancelar item).
 *
 * Tools típicas: geralmente NENHUMA (state já tem). As vezes calcularFrete pra confirmar entrega.
 *
 * Exemplos focados (9):
 *   6. Closing intent + pix sem dados completos
 *  10. Closing parcial (ack + draft)
 *  11. Intenção de fechamento SEM tools (cliente aceitou cotação anterior)
 *  12. Despedida pós-fechamento
 *  13. Nome + endereço grudados na frase (separe!)
 *  15. Cliente fechou MULTIPLOS items, pergunta total → add_to_cart x N
 *  16. Cliente pergunta total ANTES de aceitar (estimativa, NÃO add_to_cart)
 *  17. Tira UM item do carrinho (remove_from_cart)
 *  18. Muda quantidade (update_cart_item)
 *  19. Cancela TUDO (clear_cart)
 */

export const SKILL_REGISTRAR_INTENCAO_FECHAMENTO_EXAMPLES = [
  '# Exemplos da skill registrar_intencao_fechamento',
  '',
  '# REGRA DE OURO DO FECHAMENTO (LEIA PRIMEIRO)',
  '',
  'Quando cliente sinaliza fechamento ("vou levar", "fecha", "pode separar", "vou querer"),',
  'voce DEVE garantir que cada item aceito ESTA NO CART antes de pedir dados.',
  '',
  'PROCESSO (sempre nesta ordem):',
  '1. Identifique os items que o cliente ACEITOU (state.items ativos + tool_results recentes + recent_messages)',
  '2. Para CADA item aceito que NAO esta em state.cart → emit add_to_cart(product_id, qty, unit_price)',
  '3. SOMENTE DEPOIS pergunte dados faltantes (nome, endereco, pagamento)',
  '',
  'ERRO COMUM (visto na conv 611): cliente disse "cancela X e vou levar Y, fecha o pedido".',
  'Bot anotou o cancelamento, pediu nome+endereco, mas ESQUECEU de emit add_to_cart pra Y.',
  'Resultado: cart vazio no fim, pedido nunca fechou, cliente saiu sem confirmacao.',
  '',
  'NAO ASSUMA que ja tem cart. SEMPRE verifique state.cart. Se vazio E cliente acabou de',
  'aceitar produto cotado, emit add_to_cart NESTE turn.',
  '',
  '## Exemplo 6 — Closing intent + pix com produto cotado no mesmo turn',
  'Customer: "Minha moto é Zontes R310 2024. Traseiro 160/60R17. Se tiver, passo no pix hoje."',
  'tool_results: buscarProduto (P6=R$120), verificarEstoque (P6 disponível)',
  '{',
  '  "say": "Achei o 160/60R17 traseiro por R$ 120,00 e tem em estoque. Anotei pagamento via Pix. Me passa seu nome pra eu separar?",',
  '  "actions": [',
  '    create_item ITEM_A, update_slot item ITEM_A moto_modelo="R310", moto_ano=2024, medida_pneu="160/60R17", posicao_pneu="rear",',
  '    update_slot global forma_pagamento="pix",',
  '    { "type": "update_draft", "payment_method": "pix" }',
  '  ],',
  '  "claims": [',
  '    { "type": "price", "amount": 120, "product_id": "P6" },',
  '    { "type": "stock_availability", "product_id": "P6" }',
  '  ],',
  '  "rationale": "Closing sinalizado, draft com pix. Falta nome. Cita produto/estoque com claims."',
  '}',
  '',
  '## Exemplo 10 — Fechamento parcial (ack + draft sem afirmar comercial)',
  'Customer: "Pode separar o 110/70-17, pago pix e busco hoje."',
  'tool_results: depende — pode não ter rodado nesse turno (continuação de turno anterior)',
  '{',
  '  "say": "Anotei: separar 110/70-17, pagamento Pix, retirada hoje. Me passa seu nome pra registrar?",',
  '  "actions": [',
  '    update_slot global forma_pagamento="pix",',
  '    { "type": "update_draft", "payment_method": "pix", "fulfillment_mode": "pickup" }',
  '  ],',
  '  "claims": [],',
  '  "rationale": "Fechamento parcial: registra pagamento e pickup, pede nome. Nao afirma comercial novo, sem claim."',
  '}',
  '',
  '## Exemplo 11 — Aceite contextual (cliente respondeu afirmativo a oferta do bot)',
  'Bot na ultima mensagem ofereceu algo ("quer que eu separe?", "posso reservar?", "fechamos?", "vou separar pra voce?"). Cliente respondeu afirmativo de QUALQUER forma — "sim", "pode", "pode sim", "pode amigo", "pode mandar", "manda", "ok", "blz", "fechou", "bora", "isso", "tô dentro", "manda bala", etc.',
  'state.items tem produto cotado. tool_results deste turn: nenhuma (cotacao foi antes).',
  'IMPORTANTE: NAO procure frase exata. Bot ofereceu + cliente afirmou = ACEITE. Emit add_to_cart.',
  '{',
  '  "say": "Show! Anotei. Me passa seu nome completo e o endereço pra entrega (rua, número, bairro).",',
  '  "actions": [',
  '    { "type": "add_to_cart", "product_id": "<uuid_do_produto_cotado>", "quantity": 1, "unit_price": <preco_cotado> },',
  '    { "type": "update_draft", "fulfillment_mode": "delivery" }',
  '  ],',
  '  "claims": [],',
  '  "rationale": "Bot ofereceu separar/reservar + cliente respondeu afirmativo (contextual) → aceite. product_id vem do historico. Sem claim (valor cotado antes)."',
  '}',
  '',
  '## Exemplo 11b — Mensagem composta: cancela X + leva Y + fecha (REGRA CRITICA)',
  '',
  'Cliente diz 3 coisas ao mesmo tempo na mesma mensagem:',
  '  (1) Cancela um produto que estava em cotacao',
  '  (2) Aceita outro produto pra levar',
  '  (3) Sinaliza fechamento ("fecha o pedido", "fecha pra mim")',
  '',
  'Voce DEVE fazer as 3 coisas no mesmo turn:',
  '  (1) remove_from_cart do cancelado (se estava no cart) OU ignora (se nunca foi adicionado)',
  '  (2) **add_to_cart do aceito** ← NAO ESQUECA, este eh o erro classico',
  '  (3) Pergunta dados que faltam pra fechar (nome, endereco, pagamento — o que ainda nao tem)',
  '',
  'state.items: 2 items ativos. Item A (NMAX dianteiro 110/70-13 cotado R$X, product_id=PA).',
  'Item B (PCX 150 traseiro 120/70-14 cotado R$Y, product_id=PB).',
  'state.cart: VAZIO (nem o NMAX nem a PCX foram adicionados ainda — bot so cotou).',
  '',
  'Customer: "faz o seguinte cancela o da pcx e vou levar so o da nmax e fecha o pedido aí pra mim"',
  '',
  '{',
  '  "say": "Fechou. Cancelei a cotação da PCX e segui só com o da NMAX (110/70-13 dianteiro, R$ X,XX). Me passa seu nome completo e o endereço pra entrega.",',
  '  "actions": [',
  '    { "type": "add_to_cart", "product_id": "PA", "quantity": 1, "unit_price": <preco_NMAX> },',
  '    { "type": "update_draft", "fulfillment_mode": "delivery" }',
  '  ],',
  '  "claims": [],',
  '  "rationale": "Mensagem composta: cancelou PCX (nem estava no cart, so ignoro), aceitou NMAX (add_to_cart obrigatorio), e pediu fechamento (pergunto dados faltantes). NAO esqueco add_to_cart no meio do cancelamento."',
  '}',
  '',
  'VARIACAO: se a PCX JA ESTAVA no cart (state.cart contem PB), entao:',
  '  - actions inclui: { "type": "remove_from_cart", "cart_item_id": "<id_da_PCX_em_state.cart>" }',
  '  - actions inclui: { "type": "add_to_cart", "product_id": "PA", "quantity": 1, "unit_price": ... }',
  '',
  '## Exemplo 12 — Despedida pos-fechamento (RESUMO + numero do pedido)',
  'Customer: "Opa valeu" (ou "obrigado", "blz amigo", "tmj", "fechou")',
  'tool_results: NENHUMA.',
  '',
  'REGRA CRITICA: Quando cliente se despede E o pedido ja foi fechado, SEMPRE mande resumo final.',
  'Pedido fechado = state.cart tem items confirmados + state.order_draft com customer_name + delivery_address (ou pickup) + payment_method preenchidos.',
  '',
  'COMO MONTAR O RESUMO:',
  '1. Se state.order_draft.order_number existe (formato "PED-XXXX"), comeca por "Pedido #PED-XXXX confirmado:". Se nao existir ainda, comece com "Pedido confirmado:" sem numero.',
  '2. Lista TODOS os items do cart com medida + preco unitario.',
  '3. Modalidade: "Entrega: <endereco completo>" OU "Retirada na loja".',
  '4. Pagamento: forma escolhida.',
  '5. Total = soma de items + frete (se delivery).',
  '6. Encerra com "Qualquer coisa é só chamar."',
  '',
  'Exemplo state: cart=[1x 130/70-13 R$99], draft={customer_name="Antonio", delivery_address="Rua X 657, Marechal Hermes, RJ", payment_method="pix", order_number="PED-0042"}, frete cotado R$9,90.',
  '{',
  '  "say": "Show, Antônio! Pedido #PED-0042 confirmado:\\n• 1x 130/70-13 — R$ 99,00\\n• Entrega: Rua X 657, Marechal Hermes, RJ\\n• Pagamento: Pix\\n• Total: R$ 108,90 (com frete R$ 9,90)\\nQualquer coisa é só chamar.",',
  '  "actions": [],',
  '  "claims": [',
  '    { "type": "price", "amount": 99, "product_id": "<uuid_do_item>" },',
  '    { "type": "delivery_fee", "amount": 9.9 }',
  '  ],',
  '  "rationale": "Despedida apos pedido fechado. Mando resumo final com items, modalidade, pagamento, numero do pedido (PED-XXXX) e total. Claims pra autorizar money mentions."',
  '}',
  '',
  '## Exemplo 12b — Despedida SEM pedido fechado (so cordialidade)',
  'Cliente se despede mas state.cart vazio OU state.order_draft sem dados completos (ainda esta cotando, nao fechou).',
  'Customer: "valeu, vou pensar"',
  '{',
  '  "say": "Disponha! Qualquer coisa é só chamar.",',
  '  "actions": [],',
  '  "claims": [],',
  '  "rationale": "Despedida sem pedido fechado. So cordialidade, sem resumo (nao ha o que resumir)."',
  '}',
  '',
  '## Exemplo 13 — Nome + endereco grudados (separar + confirmar completo)',
  'Separe nome (so o nome) de endereco (rua/numero/bairro). Confirme endereco COMPLETO incluindo cidade do state (Show, dont ask).',
  'Customer: "Anderson Tavares endereço rua vagabanda n 656 bangu"',
  'state.global_slots: municipio="Rio de Janeiro" (de calcularFrete anterior)',
  '{',
  '  "say": "Anotei, Anderson Tavares. Endereço: Rua Vagabanda nº 656, Bangu, Rio de Janeiro. Tá certo?",',
  '  "actions": [',
  '    update_slot global nome="Anderson Tavares", update_slot global bairro="Bangu",',
  '    { "type": "update_draft", "customer_name": "Anderson Tavares", "delivery_address": "Rua Vagabanda nº 656, Bangu, Rio de Janeiro", "fulfillment_mode": "delivery" }',
  '  ],',
  '  "claims": [],',
  '  "rationale": "Separo nome/endereco. Cidade do state. Cliente confirma/corrige."',
  '}',
  '',
  '## Exemplo 13b — Pagamento generico → mostra parcelas direto',
  'Customer: "vou pagar no cartao"',
  '{',
  '  "say": "Anotei. Cartao credito (aceitamos ate 3x sem juros) ou debito?",',
  '  "actions": [ update_slot global forma_pagamento="cartao" ],',
  '  "claims": [],',
  '  "rationale": "Cartao generico. Mostro parcelas (politica) ja na pergunta — cliente decide informado."',
  '}',
  '',
  '## Exemplo 15 — Aceite multi-item (total preemptivo)',
  '2 items cotados antes (140/70-17 R$99, 80/100-18 R$99), frete R$9,90. Cliente aceita.',
  'Customer: "blz pode fechar" (ou "vou querer os 2", "fechado")',
  '{',
  '  "say": "Show. Fechado os 2: o 140/70-17 R$ 99,00 e o 80/100-18 R$ 99,00. Com frete R$ 9,90, total R$ 207,90. Me passa seu nome pra eu separar?",',
  '  "actions": [',
  '    { "type": "add_to_cart", "product_id": "<uuid_traseiro>", "quantity": 1, "unit_price": 99 },',
  '    { "type": "add_to_cart", "product_id": "<uuid_dianteiro>", "quantity": 1, "unit_price": 99 }',
  '  ],',
  '  "claims": [],',
  '  "rationale": "Multi-item aceito. 2 add_to_cart qty=1. Total preemptivo 207,90 (sem cliente perguntar). Sem claim novo."',
  '}',
  '',
  '## Exemplo 16 — Cliente pergunta total DURANTE coleta, sem fechar ainda',
  'Cenario: 1 item cotado, cliente em meio da coleta de endereco. Cliente pergunta "quanto vai dar tudo?" ANTES de aceitar.',
  '{',
  '  "say": "Pelo que temos ate aqui: o 130/70-13 R$ 99,00 + frete R$ 9,90 = R$ 108,90. Posso confirmar?",',
  '  "actions": [],',
  '  "claims": [],',
  '  "rationale": "Pediu total sem aceitar. Mostro estimativa. NAO add_to_cart antes de aceite explicito."',
  '}',
  '',
  '## Exemplo 17 — Tira UM item (cita QUAL + preco)',
  'state.cart: CART_A dianteiro 80/100-18 R$99, CART_B traseiro 90/90-18 R$99. Cliente desiste do traseiro.',
  'Customer: "esquece o traseiro, vou levar so o dianteiro"',
  '{',
  '  "say": "Show, tirei o 90/90-18 traseiro (R$ 99,00). Fica so o 80/100-18 dianteiro (R$ 99,00). Total agora R$ 99,00 + frete. Mantem o resto?",',
  '  "actions": [ { "type": "remove_from_cart", "cart_item_id": "CART_B" } ],',
  '  "claims": [],',
  '  "rationale": "Removi traseiro. Cito item+preco removido + total novo. Sem claim."',
  '}',
  '',
  '## Exemplo 18 — Muda quantidade (qty=TOTAL desejado, nao incremento)',
  'state.cart: CART_A 130/70-13 qty=1 R$99. Cliente quer 2.',
  'Customer: "vou levar 2 desse mesmo"',
  '{',
  '  "say": "Beleza, 2 unidades do 130/70-13 (R$ 99,00 cada). Total R$ 198,00 + frete. Confirma?",',
  '  "actions": [ { "type": "update_cart_item", "cart_item_id": "CART_A", "quantity": 2 } ],',
  '  "claims": [],',
  '  "rationale": "Subiu pra 2. Cito unitario+total. quantity=2 (total, nao incremento)."',
  '}',
  '',
  '## Exemplo 19 — Cancela TUDO (lista o que cancelou)',
  'state.cart: 2 items, total R$ 198. Cliente desiste.',
  'Customer: "esquece, deixa pra outro dia" (ou "cancela tudo", "muda de ideia")',
  '{',
  '  "say": "Tranquilo, cancelei o pedido (2 pneus, R$ 198,00). Qualquer coisa, e so chamar.",',
  '  "actions": [ { "type": "clear_cart" } ],',
  '  "claims": [],',
  '  "rationale": "Cancelou explicito. Listo o que cancelei. Se ambiguo (\\"hmm nao sei\\"), pergunte antes."',
  '}',
].join('\n');
