/**
 * Skill `registrar_intencao_fechamento` — aceite + carrinho + draft.
 *
 * Quando: cliente sinaliza fechamento ("vou levar", "pode fechar", "vou ficar com"),
 * ou está preenchendo dados de fechamento (nome, endereço, pagamento, modalidade),
 * ou pede pra mexer no carrinho (tirar/mudar/cancelar item).
 *
 * Tools típicas: geralmente NENHUMA (state já tem). As vezes calcularFrete pra confirmar entrega.
 *
 * Exemplos focados (9):
 *   6. Closing intent + pix sem dados completos
 *  10. Closing parcial (ack + draft)
 *  11. Intenção de fechamento SEM tools (cliente aceitou cotação anterior)
 *  12. Despedida pós-fechamento
 *  13. Nome + endereço grudados na frase (separe!)
 *  15. Cliente fechou MULTIPLOS items, pergunta total → add_to_cart x N
 *  16. Cliente pergunta total ANTES de aceitar (estimativa, NÃO add_to_cart)
 *  17. Tira UM item do carrinho (remove_from_cart)
 *  18. Muda quantidade (update_cart_item)
 *  19. Cancela TUDO (clear_cart)
 */

export const SKILL_REGISTRAR_INTENCAO_FECHAMENTO_EXAMPLES = [
  '# Exemplos da skill registrar_intencao_fechamento',
  '',
  '## Exemplo 6 — Closing intent + pix com produto cotado no mesmo turn',
  'Customer: "Minha moto é Zontes R310 2024. Traseiro 160/60R17. Se tiver, passo no pix hoje."',
  'tool_results: buscarProduto (P6=R$120), verificarEstoque (P6 disponível)',
  '{',
  '  "say": "Achei o 160/60R17 traseiro por R$ 120,00 e tem em estoque. Anotei pagamento via Pix. Me passa seu nome pra eu separar?",',
  '  "actions": [',
  '    create_item ITEM_A, update_slot item ITEM_A moto_modelo="R310", moto_ano=2024, medida_pneu="160/60R17", posicao_pneu="rear",',
  '    update_slot global forma_pagamento="pix",',
  '    { "type": "update_draft", "payment_method": "pix" }',
  '  ],',
  '  "claims": [',
  '    { "type": "price", "amount": 120, "product_id": "P6" },',
  '    { "type": "stock_availability", "product_id": "P6" }',
  '  ],',
  '  "rationale": "Closing sinalizado, draft com pix. Falta nome. Cita produto/estoque com claims."',
  '}',
  '',
  '## Exemplo 10 — Fechamento parcial (ack + draft sem afirmar comercial)',
  'Customer: "Pode separar o 110/70-17, pago pix e busco hoje."',
  'tool_results: depende — pode não ter rodado nesse turno (continuação de turno anterior)',
  '{',
  '  "say": "Anotei: separar 110/70-17, pagamento Pix, retirada hoje. Me passa seu nome pra registrar?",',
  '  "actions": [',
  '    update_slot global forma_pagamento="pix",',
  '    { "type": "update_draft", "payment_method": "pix", "fulfillment_mode": "pickup" }',
  '  ],',
  '  "claims": [],',
  '  "rationale": "Fechamento parcial: registra pagamento e pickup, pede nome. Nao afirma comercial novo, sem claim."',
  '}',
  '',
  '## Exemplo 11 — Aceite sem tool nova (cliente aceitou cotacao anterior)',
  'Customer disse algo como "blz vou querer" / "vou ficar com esse" / "pode fechar" / "fica esse mesmo" / "tá bom esse" / "fecha" / "manda esse" / "pode separar".',
  'state.items tem 1 produto cotado em turn anterior (com product_id valido em recent_tool_results).',
  'tool_results: NENHUMA neste turn (cotacao ja foi feita antes).',
  'IMPORTANTE: TODAS essas frases sao ACEITE EXPLICITO. Emit add_to_cart com product_id do historico.',
  '{',
  '  "say": "Show! Anotei. Me passa seu nome completo e o endereço pra entrega em Bangu (rua, número).",',
  '  "actions": [',
  '    { "type": "add_to_cart", "product_id": "<uuid_do_produto_cotado>", "quantity": 1, "unit_price": <preco_cotado> },',
  '    { "type": "update_draft", "fulfillment_mode": "delivery" }',
  '  ],',
  '  "claims": [],',
  '  "rationale": "Aceite explicito de produto cotado antes. Historico (recent_tool_results) tem o product_id valido. Emit add_to_cart com o id daquele produto. NAO precisa nova tool nem record_offer no turn atual. Sem claim — valor ja foi cotado e validado em turn anterior."',
  '}',
  '',
  '## Exemplo 12 — Despedida pos-fechamento',
  'Customer: "Opa valeu"  (ou "obrigado", "blz amigo", "tmj")',
  'tool_results: NENHUMA.',
  '{',
  '  "say": "Disponha! Qualquer coisa é só chamar.",',
  '  "actions": [],',
  '  "claims": [],',
  '  "rationale": "Despedida apos fechamento. Encerro com cordialidade. Sem actions porque nao tem dado novo. Sem fallback — despedida nao eh falta de dado."',
  '}',
  '',
  '## Exemplo 13 — Cliente passa nome E endereco grudados na mesma frase',
  'IMPORTANTE: separe semanticamente o nome (so o nome) do endereco (rua/numero/bairro/complemento).',
  'NAO ponha "endereço rua x" no customer_name. NAO ponha "Anderson Tavares" no delivery_address.',
  'Customer: "Anderson Tavares endereço rua vagabanda n 656 bangu"',
  '{',
  '  "say": "Anotei, Anderson Tavares. Endereço confirmado: rua Vagabanda nº 656, Bangu. Confirma se ta certo?",',
  '  "actions": [',
  '    update_slot global nome="Anderson Tavares",',
  '    update_slot global bairro="Bangu",',
  '    { "type": "update_draft", "customer_name": "Anderson Tavares", "delivery_address": "rua Vagabanda nº 656, Bangu", "fulfillment_mode": "delivery" }',
  '  ],',
  '  "claims": [],',
  '  "rationale": "Cliente passou nome+endereco juntos. Separo semanticamente: nome=Anderson Tavares, endereco=rua Vagabanda nº 656 Bangu. update_draft com campos separados."',
  '}',
  '',
  '## Exemplo 15 — Cliente fechou MULTIPLOS items, pergunta total',
  'Cenario: dois items cotados em turns anteriores (item A = 140/70-17 R$ 99, item B = 80/100-18 R$ 99). Frete R$ 9,90 cotado. Cliente diz "blz pode fechar quanto deu tudo?".',
  'tool_results: nenhuma (state ja tem tudo).',
  '{',
  '  "say": "Show. Fechado os 2: o 140/70-17 R$ 99,00 e o 80/100-18 R$ 99,00. Com frete de R$ 9,90, total R$ 207,90. Confirma a forma de pagamento?",',
  '  "actions": [',
  '    { "type": "add_to_cart", "product_id": "<uuid_traseiro>", "quantity": 1, "unit_price": 99 },',
  '    { "type": "add_to_cart", "product_id": "<uuid_dianteiro>", "quantity": 1, "unit_price": 99 }',
  '  ],',
  '  "claims": [],',
  '  "rationale": "Fechando E pedindo total. Emit add_to_cart pros 2 aceitos. Soma state.items + delivery_fee = 207,90. Sem claim novo (valores cotados antes)."',
  '}',
  '',
  '## Exemplo 16 — Cliente pergunta total DURANTE coleta, sem fechar ainda',
  'Cenario: 1 item cotado, cliente em meio da coleta de endereco. Cliente pergunta "quanto vai dar tudo?" ANTES de aceitar.',
  '{',
  '  "say": "Pelo que temos ate aqui: o 130/70-13 R$ 99,00 + frete R$ 9,90 = R$ 108,90. Posso confirmar?",',
  '  "actions": [],',
  '  "claims": [],',
  '  "rationale": "Pediu total sem aceitar. Mostro estimativa. NAO add_to_cart antes de aceite explicito."',
  '}',
  '',
  '## Exemplo 17 — Cliente tira UM item do carrinho',
  'Cenario: state.cart tem 2 items (id=CART_A dianteiro 80/100-18, id=CART_B traseiro 90/90-18). Cliente desiste do traseiro.',
  'Customer: "Ah, esquece o traseiro, vou levar so o dianteiro mesmo"',
  '{',
  '  "say": "Show, tirei o 90/90-18 traseiro. Fica so o 80/100-18 dianteiro entao. Mantem o resto igual?",',
  '  "actions": [ { "type": "remove_from_cart", "cart_item_id": "CART_B" } ],',
  '  "claims": [],',
  '  "rationale": "Desistiu do traseiro. CART_B vem de state.cart. Sem claim."',
  '}',
  '',
  '## Exemplo 18 — Cliente muda quantidade',
  'Cenario: state.cart tem 1 item (CART_A, 130/70-13 quantity=1). Cliente quer 2.',
  'Customer: "Na verdade vou levar 2 desse mesmo"',
  '{',
  '  "say": "Beleza, ajustei pra 2 unidades do 130/70-13. Total agora R$ 198,00 + frete. Confirma?",',
  '  "actions": [ { "type": "update_cart_item", "cart_item_id": "CART_A", "quantity": 2 } ],',
  '  "claims": [],',
  '  "rationale": "Subiu qty. cart_item_id de state.cart. Valor 2x99 vem de history."',
  '}',
  '',
  '## Exemplo 19 — Cliente cancela TUDO',
  'Cenario: state.cart com 1+ items. Cliente desiste do pedido inteiro.',
  'Customer: "Esquece, deixa pra outro dia" (ou "cancela tudo", "to fora", "muda de ideia")',
  '{',
  '  "say": "Tranquilo, cancelei o pedido. Qualquer coisa, e so chamar.",',
  '  "actions": [ { "type": "clear_cart" } ],',
  '  "claims": [],',
  '  "rationale": "Cancelou explicito. clear_cart zera. Se ambiguo (\\"hmm nao sei\\"), pergunte antes de zerar."',
  '}',
].join('\n');
