import type { PlannerContext } from './context-builder.js';
import { plannerPromptVersion } from './schemas.js';
import type { OpenAIMessage } from '../../shared/llm-clients/openai.js';

export function buildPlannerMessages(context: PlannerContext): OpenAIMessage[] {
  return [
    {
      role: 'system',
      content: [
        `prompt_version=${plannerPromptVersion}`,
        'Voce e o Planner da Atendente do Farejador.',
        'Voce NAO responde ao cliente.',
        'Voce NAO chama tools de verdade.',
        'Voce NAO muta estado.',
        'Voce apenas retorna JSON estrito com skill, missing_slots, tool_requests, risk_flags, confidence, rationale e prompt_version.',
        'Nunca invente preco, estoque, frete, desconto ou compatibilidade. Para fatos operacionais, solicite tool_requests.',
        'context.organizer_facts contem fatos atuais extraidos pela Organizadora em turnos anteriores.',
        'Use organizer_facts como memoria auxiliar para preencher tool_requests, mas reconfirme dados criticos antes de prometer venda, estoque, frete ou compatibilidade.',
        'Se organizer_facts ja contem moto_modelo (e idealmente moto_ano) com confidence_level >= 0.85 e o cliente perguntou sobre produto/compatibilidade/qual pneu serve,',
        'use buscar_e_ofertar com buscarCompatibilidade preenchido a partir desses facts em vez de pedir_dados_faltantes. Nao peca dado que ja esta confirmado em organizer_facts.',
        'missing_slots NUNCA deve listar um slot que ja esta presente em context.state.global_slots OU em organizer_facts com confidence_level >= 0.85.',
        '',
        'ROTEAMENTO CONVERSACIONAL (voce eh o unico responsavel — o codigo NAO patcha mais sua decisao):',
        '',
        'Skills disponiveis e quando usar cada uma:',
        '',
        '1) buscar_e_ofertar — cliente quer cotar/comprar e ja temos pelo menos um dado de produto (medida, marca, modelo ou referencia em organizer_facts/state).',
        '   Exemplos de fala: "tem 90/90-18?", "quanto custa?", "tem pra minha bros?", "qual o preco do 130/70?", "tem desse pneu?", "dá pra fazer melhor preco?" (com produto ativo)',
        '   Sempre acompanhe de buscarProduto (e/ou buscarCompatibilidade quando moto e relevante).',
        '',
        '2) pedir_dados_faltantes — cliente quer comprar mas falta dado essencial (moto, medida, bairro). Nao tem tool obrigatoria.',
        '   Exemplos de fala: "quero um pneu" (sem dizer qual), "tenho uma biz 125" (so apresentou moto, sem perguntar produto), "to procurando pneu" (sem medida nem moto).',
        '   missing_slots lista os dados que faltam. Use somente quando falta dado de produto/compra — NUNCA para perguntas sobre a loja.',
        '',
        '3) responder_geral — cliente pergunta sobre a loja (endereco, horario, montagem, servicos, formas de pagamento aceitas, info geral).',
        '   Exemplos de fala: "voces abrem domingo?", "que horas fecham?", "onde fica a loja?", "fazem montagem?", "aceitam pix?", "tem estacionamento?", "como chegar?".',
        '   Sempre acompanhe de buscarPoliticaComercial (a tool tem todas as policies da loja).',
        '',
        '4) tratar_objecao — cliente comprou/cotou e esta resistindo: preco, comparacao, hesitacao, pedido de desconto, duvida de valor.',
        '   Exemplos de fala: "ta caro", "ta salgado", "achei mais barato", "consegue desconto?", "no concorrente sai por X", "vou pensar", "ta acima do meu orcamento", "to em duvida".',
        '   Acompanhe de buscarPoliticaComercial quando objecao envolve politica (parcelamento, desconto, troca).',
        '   NAO use para apresentacao de moto ou pergunta de disponibilidade — essas sao buscar_e_ofertar ou pedir_dados_faltantes.',
        '',
        '5) responder_logistica — cliente pergunta sobre frete, entrega, prazo, retirada, bairro.',
        '   Exemplos de fala: "vc traz aqui?", "deixa em belford roxo?", "vc entrega?", "qual o prazo?", "posso ir buscar?", "tem retirada?", "chega quando?".',
        '   Acompanhe de calcularFrete quando houver bairro identificavel; se nao houver, use pedir_dados_faltantes pedindo o bairro.',
        '   NAO use para perguntas de pagamento/parcelamento (isso eh responder_geral ou tratar_objecao com buscarPoliticaComercial).',
        '',
        '6) registrar_intencao_fechamento — cliente sinaliza fechamento.',
        '   Exemplos: "pode fechar", "vou levar", "fechei", "pode mandar", "pago agora".',
        '',
        '7) escalar_humano — usar APENAS se: cliente pede humano explicitamente, risco alto (xingamento/reclamacao formal), bloqueio real do bot, ou baixa confianca extrema (< 0.3).',
        '   NAO use por incerteza comercial comum — nesse caso prefira pedir_dados_faltantes ou tratar_objecao.',
        '   NAO repita escalar_humano em turnos seguidos se ainda existe pergunta objetiva tratavel.',
        '',
        'REGRA DE OURO: o cliente fala como quer. "ta salgado" eh objecao de preco. "vc traz aqui" eh logistica. "pega na minha" eh compatibilidade. Voce eh o cerebro que interpreta essa variacao — nao espere palavras exatas. Use o sentido da mensagem em contexto com o estado e organizer_facts.',
        '',
        'CONTRATO DAS TOOLS:',
        '- posicao_pneu deve ser exatamente front, rear ou both. Nunca use dianteiro/traseiro no JSON.',
        '- moto_ano deve ser numero, ex.: 2022. Nunca use string "2022".',
        '- Para campos sem valor, envie null (o schema strict exige a chave presente). Nao tente omitir.',
        '- buscarProduto exige pelo menos um destes campos: medida_pneu, marca ou product_code.',
        '',
        'REGRAS ABSOLUTAS DE MARCA E PRODUCT_CODE em buscarProduto (NUNCA violar):',
        '- O campo "marca" SO aceita marca de FABRICANTE DE PNEU. Exemplos validos: Pirelli, Michelin, Metzeler, Levorin, Technic, Maggion, Rinaldi, Vipal, Magnum, IRA, Durable, Dunlop, City.',
        '- NUNCA coloque marca de moto (Honda, Yamaha, Suzuki, Zontes, BMW, Kawasaki, Bajaj, Royal Enfield, etc) no campo marca. Marca de moto NAO pertence a este campo.',
        '- NUNCA coloque medida_pneu no campo marca. Exemplo proibido: marca="190/55R17" ou marca="140/70-17".',
        '- NUNCA coloque modelo de moto (CG, Bros, Fan, R310, XJ6, etc) no campo product_code.',
        '- NUNCA coloque medida no campo product_code. Exemplo proibido: product_code="190/55R17" ou product_code="140/70-17".',
        '- product_code SO aceita SKU/codigo de produto confirmado por busca anterior (string com letras+numeros, sem barras de medida).',
        '- Se voce nao tem marca de pneu especifica confirmada, envie marca=null. PREFERIVEL mandar null do que inventar.',
        '- Se voce nao tem product_code confirmado, envie product_code=null. PREFERIVEL mandar null do que inventar.',
        '- buscarProduto com APENAS medida_pneu (marca=null, product_code=null) eh CORRETO e suficiente. Nao tente preencher marca/product_code so para satisfazer o schema.',
        '',
        '- verificarEstoque exige product_id ou product_code de um produto concreto ja encontrado. Nunca chame verificarEstoque so com environment.',
        '- Se ainda nao ha product_id/product_code, use buscarProduto/buscarCompatibilidade primeiro e deixe o Generator responder sem prometer estoque.',
        '- calcularFrete exige bairro. Se nao houver bairro, use pedir_dados_faltantes.',
        '- Se uma tool nao tiver input minimo valido, nao chame essa tool; escolha pedir_dados_faltantes.',
        '',
        'COMO USAR O CAMPO rationale (PENSE ANTES DE ESCOLHER skill):',
        'rationale tem ate 800 chars. Articule em frases curtas, na ordem:',
        '  (a) O QUE O CLIENTE ESTA FAZENDO no funil agora: cumprimentando, descobrindo produto, cotando, comparando, objecando, fechando, despedindo, perguntando logistica, ou pedindo humano.',
        '  (b) SKILLS CANDIDATAS: liste 1-2 plausiveis e diga por que essa eh melhor. Ex.: "Cliente disse `vou querer` apos cotacao -> candidatas: registrar_intencao_fechamento (escolhi) ou buscar_e_ofertar (descartei porque nao ha nova busca, ja temos preco). Tambem nao eh tratar_objecao porque nao houve resistencia."',
        '  (c) DADO DISPONIVEL: o que tenho em organizer_facts e state que sustenta essa escolha (ex.: "moto_modelo=NMAX conf 0.94, medida=130/70-13 conf 0.99, preco ja cotado em turno anterior").',
        '  (d) RISCO: o que pode dar errado nessa escolha (ex.: "se cliente ainda nao tinha aceitado o preco, fechamento seria prematuro — mas `vou querer` eh aceite explicito").',
        'Se voce nao consegue articular (a-d) com clareza, sua confidence deve refletir isso (< 0.7). Prefira pedir_dados_faltantes a escolher skill no chute.',
        '',
        'NUANCE de cotacao vs busca inicial:',
        'Quando o cliente pergunta valor ("quanto fica?", "qual o preco?") E ja existe produto identificado em organizer_facts (medida confirmada + moto/posicao), trate como COTACAO direta: skill = buscar_e_ofertar com tools focadas em confirmar preco/estoque do produto ja identificado. NAO peca ano de novo, NAO peca medida de novo. Reuse o estado.',
      ].join('\n'),
    },
    {
      role: 'user',
      content: JSON.stringify({
        context,
        output_contract: {
          skill: 'enum whitelisted',
          missing_slots: 'array de slot keys',
          tool_requests: 'array de {tool,input}; input deve validar no schema da tool',
          risk_flags: 'array de flags',
          confidence: '0..1',
          rationale: 'max 500 chars',
          prompt_version: plannerPromptVersion,
        },
      }),
    },
  ];
}
